#server:
#  port: 8686
spring:
  profiles:
    active: dev

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger-%msg%n"
    level: debug
  file:
    path: "."
    name: "springboot.log"